### ISSUE TITLE
FBCUNN package required?

### ISSUE THREAD

**Issue by hohoCode** [facebook/NAMAS#1]
Hi,

Thanks a lot for your work and the wonderful opensource repo. Just a quick question, is this package 'fbcunn' required by your opensource tool as indicated in the README? 

I ran a search and saw the line "require 'fbcunn' " it is commented out in the encoder.lua file, so does that mean your tool does not need 'fbcunn' package? 'fbcunn' package seems to only work on Ubuntu, which may have some limits... so that is why I am asking this question. Thanks!

**Comment by supchop** [comment]
Hi There, 

No. The package does NOT require fbcunn. You can run it using the open source torch. Sorry for the confusion. I'll update the readme shortly. 

Thanks, 
Sumit

**Comment by hohoCode** [comment]
Thanks again for your wonderful opensource!

**Comment by ayanamongol** [comment]
nn.TemporalKMaxPooling in beam_search.lua is from fbcunn... Am I right?

**Comment by falcondai** [comment]
@ayanamongol i think so. so far, the easiest way to set up `fbcunn` i found is to follow the installation of [`fblualib`](https://github.com/facebook/fblualib) and then `fbnn` and `fbcunn`. After that, change the `nn` dependency in `summary/run.lua` to `fbcunn`. I really wish that Facebook would release their rocks via luarocks or maybe fbluarocks :wink: ?

**Comment by saurfang** [comment]
After sweat and tears getting `fbcunn` running on EC2 finally, I realized replacing the `find_k_max` works just as well. You can comment out the `TemporalKMaxPooling` variable if you don't want to import `fbcunn` and need to make sure pass the beam size into the function down below.

``` lua
local function find_k_max(k, mat)
   return mat:topk(2*k, true)
end
```

**Comment by arwhirang** [comment]
@saurfang Thank you so much! But, could you be more specific, please? The find_k_max function is not a new function in beam_search.lua, I guess?

I just installed fbcunn. If anyone suffers from the nn.thnn missing problem, do the following
luarocks install nn
luarocks install cunn

**Comment by jeiranj** [comment]
@falcondai : did you also replace the nn dependency in summary/nnlm.lua?

**Comment by falcondai** [comment]
i dont think so. you can take a look at my fork: https://github.com/falcondai/NAMAS

**Comment by yaserkl** [comment]
@saurfang When I replace the find_k_max function with yours, I'll get the following error:
summary/beam_search.lua:63: attempt to call method 'topk' (a nil value)

and when I try to use the original find_k_max function, I'm getting the following error (even after replacing nn with fbcunn:
torch-distro/extra/cutorch/lib/THC/THCTensorMathPairwise.cu(47) : cuda runtime error (8) : invalid device function stack traceback:
        [C]: in function 'add'
        summary/beam_search.lua:61: in function 'find_k_max'
        summary/beam_search.lua:152: in function 'generate'
        summary/run.lua:86: in function 'main'
        summary/run.lua:121: in main chunk
any comments?

@falcondai I also tried your repo, but it gave me the same error.

**Comment by saurfang** [comment]
@arwhirang @yaserkl This has been a while but my best guess of what I did is after replacing the function `find_k_max`

1. comment out `   local pool = nn.TemporalKMaxPooling(2*K)`
2. replace `      local max_scores, mat_indices = find_k_max(pool, out:cuda())` with `       local max_scores, mat_indices = find_k_max(K, out)`

**Comment by yaserkl** [comment]
@saurfang I did exactly that, but I'm still getting this error:
/home/ubuntu/torch-distro/install/bin/luajit: summary/beam_search.lua:63: attempt to call method 'topk' (a nil value)
stack traceback:
	summary/beam_search.lua:63: in function 'find_k_max'
	summary/beam_search.lua:152: in function 'generate'
	summary/run.lua:86: in function 'main'
	summary/run.lua:121: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

If only there was one repo, which could be run successfully on a sample of data, I would know what is exactly the problem. however even the @falcondai's repo, has this problem.

**Comment by falcondai** [comment]
> torch-distro/extra/cutorch/lib/THC/THCTensorMathPairwise.cu(47) : cuda runtime error (8) : invalid device function stack traceback:

this suggests to me that there is something wrong with the GPU device selected. Note in that the original repo, it assumes the existence of 2 GPU: https://github.com/facebook/NAMAS/blob/a45675e19e24f32133ca8545e9b8267804bfd719/summary/run.lua#L26

sorry that i have not been following torch updates in general (switched to tensorflow and quite happy with it) so i do not know if some of these later issues are due to version differences. The best solution IMO would be to bake a docker image with frozen versions and let people run it via nvidia-docker.
