### ISSUE TITLE
invalid device ordinal problem

### ISSUE THREAD

**Issue by arwhirang** [facebook/NAMAS#11]
Hello, 
I came here looking for the invalid device ordinal problem appeared during the excution of the test.sh file.

Below are the console error messages I received :

THCudaCheck FAIL file=/root/torch/extra/cutorch/init.c line=698 error=10 : invalid device ordinal
/root/torch/install/bin/luajit: summary/run.lua:26: cuda runtime error (10) : invalid device ordinal at /root/torch/extra/cutorch/init.c:698
stack traceback:
[C]: in function 'setDevice'
summary/run.lua:26: in main chunk
[C]: in function 'dofile'
/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670

I think the sentence below is the most important message.
/root/torch/extra/cutorch/init.c line=698 error=10 : invalid device ordinal

My system is Ubuntu 14.04 and I installed and tested samples of CUDA-7.5 with no problems.
I tried to reinstall the NVIDIA drivers and CUDA with no avail.
It is weird that usual(google-searched) invalid device ordinal problem was solved by blacklisting nouveau, however, in my case, it does not work.

Any help please?

**Comment by arwhirang** [comment]
Hmm, I'm not sure if this is the right solution, however, I found that in the summary/run.lua, 
the function setDevice's parameter was defined as just 2. I found that my cutorch.getDevice() returned 1.

**Comment by magic282** [comment]
Thanks for your response @arwhirang . I change the device number to 1. However it has another error.

```
./summary/beam_search.lua:103: attempt to call field 'TemporalKMaxPooling' (a nil value)
stack traceback:
        ./summary/beam_search.lua:103: in function 'generate'
        summary/run.lua:86: in function 'main'
        summary/run.lua:121: in main chunk
        [C]: in function 'dofile'
        ...zhou/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

Do you know about this error?
Actually during training I had an error about fbnn. The author told me to just comment `require('fnbb')` in `nnlm.lua` out and it did worked. I don't know if this is related.

**Comment by arwhirang** [comment]
Hmm. I can't say that I know it. Maybe other people is more knowledgeble
than me?

Hope it works!
1. 7. 25. 오후 3:50에 "magic282" notifications@github.com님이 작성:

**Comment by atana1** [comment]
@magic282 , Hi I also got same error(see below) while running test.sh. Were you able to fix it?

./summary/beam_search.lua:103: attempt to call field 'TemporalKMaxPooling' (a nil value)
stack traceback:
        ./summary/beam_search.lua:103: in function 'generate'
        summary/run.lua:86: in function 'main'
        summary/run.lua:121: in main chunk
        [C]: in function 'dofile'
        ...dave/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
