### ISSUE TITLE
About fblualib: fb.util

### ISSUE THREAD

**Issue by ayanamongol** [facebook/NAMAS#2]
Hi, Thanks for the sharing first, It's really interesting...

And also, when i try to run it on my Ubuntu 14.04 system, there were following errors, I would really appreciate it if you can tell me what's going on

ayana@nlplinuxgpu:/data/disk1/private/ayana/NAMAS-master$ ./train_model.sh working_dir/ model.th
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/trepl/init.lua:363: module 'fb.util' not found:No LuaRocks module found for fb.util
    no field package.preload['fb.util']
    no file '/global-hadoop/home/ayana/.luarocks/share/lua/5.1/fb/util.lua'
    no file '/global-hadoop/home/ayana/.luarocks/share/lua/5.1/fb/util/init.lua'
    no file '/usr/local/share/lua/5.1/fb/util.lua'
    no file '/usr/local/share/lua/5.1/fb/util/init.lua'
    no file '/data/disk1/private/ayana/NAMAS-master/fb/util.lua'
    no file '/global-hadoop/home/ayana/.luarocks/lib/lua/5.1/fb/util.so'
    no file '/usr/local/lib/lua/5.1/fb/util.so'
    no file './fb/util.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/global-hadoop/home/ayana/.luarocks/lib/lua/5.1/fb.so'
    no file '/usr/local/lib/lua/5.1/fb.so'
    no file './fb.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/trepl/init.lua:363: in function 'require'
    /data/disk1/private/ayana/NAMAS-master/summary/train.lua:17: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
    [C]: at 0x00406260

It seem to me like the fblualib is missing , I tried to install it several times, but it always fail at the folly and fbthrifh part.
I read the source code and i did not see any of them are required...
I am very new to all of these and ...
Thanks for your time and patience...

**Comment by rgp90** [comment]
Hi @ayanamongol ,

I have the same problem,
How did you solve this problem?

I would really appreciate in advance.
