### ISSUE TITLE
about fbnn in nnlm.lua

### ISSUE THREAD

**Issue by ayanamongol** [facebook/NAMAS#3]
Hi,there

Last time i popped a question about fblualib, I can't install it on my system.
Then i found out only the fbnn module in is related to that, So i just deleted it .
Now the program is working, like:

ayana@nlplinuxgpu:/data/disk1/private/ayana/NAMAS-master$ tail -f train.log
Encoder model: BoW + Attention
64      200

 108838
     64
[torch.LongStorage of size 2]

torch.CudaTensor
[Running Validation]
[perp: 113252.112532 validation: 11.637372 total: 117626]
[saving mlp: working_dir//models/model.th]
[Loss: inf Epoch: 1 Position: 64 Rate: 0.100000 Time: 0.089436]
[Loss: 10.816063 Epoch: 1 Position: 6464 Rate: 0.100000 Time: 10.614009]
[Loss: 11.075415 Epoch: 1 Position: 12864 Rate: 0.100000 Time: 10.651449]
[Loss: 10.293554 Epoch: 1 Position: 19264 Rate: 0.100000 Time: 10.650220]
[Loss: 9.971358 Epoch: 1 Position: 25664 Rate: 0.100000 Time: 10.652008]
[Loss: 9.690861 Epoch: 1 Position: 32064 Rate: 0.100000 Time: 10.649381]
[Loss: 9.491403 Epoch: 1 Position: 38464 Rate: 0.100000 Time: 10.650344]
[Loss: 9.084007 Epoch: 1 Position: 44864 Rate: 0.100000 Time: 10.652305]
[Loss: 8.958983 Epoch: 1 Position: 51264 Rate: 0.100000 Time: 10.651511]
[Loss: 8.976383 Epoch: 1 Position: 57664 Rate: 0.100000 Time: 10.653925]
[Loss: 8.875211 Epoch: 1 Position: 64064 Rate: 0.100000 Time: 10.653495]
[Loss: 8.884078 Epoch: 1 Position: 70464 Rate: 0.100000 Time: 10.655499]
[Loss: 8.820546 Epoch: 1 Position: 76864 Rate: 0.100000 Time: 10.658177]
[Loss: 8.710104 Epoch: 1 Position: 83264 Rate: 0.100000 Time: 10.661504]
[Loss: 8.732778 Epoch: 1 Position: 89664 Rate: 0.100000 Time: 10.656001]
[Loss: 8.655664 Epoch: 1 Position: 96064 Rate: 0.100000 Time: 10.667066]
.....

Is it working well?

**Comment by KelleyYin** [comment]
If deleted the `require 'fbnn'` module, the program results is correct ?
Would the experiment results be affected ?
