### ISSUE TITLE
Why does the test set contain 340000 sentences ？ 

### ISSUE THREAD

**Issue by KelleyYin** [facebook/NAMAS#30]
I used the command `cat $SPLITS/test.splits  | xargs cat > test.data.txt` to build test set . My test set file contain about 340000 sentences, however, the test set mentioned in your paper only includes 2000 sentences .
What about the reason?

**Comment by jiahuanluo** [comment]
你好！我想问一下你是怎么拿到这个gigaword这个数据集的呢？我写了申请，没有回复。我现在很需要这个数据集，谢谢你！

**Comment by zdou0830** [comment]
Hi @KelleyYin, have you figured out the reason?

**Comment by raphael-sch** [comment]
The 2000 sentences mentioned in the paper are a subset of those 340T. Chopra et al. 2016 clean those 2000 by removing instances with no input, resulting in 1951 test instances. You can download them here: https://github.com/harvardnlp/sent-summary
