### ISSUE TITLE
Question about using the plain gigaword dataset

### ISSUE THREAD

**Issue by falcondai** [facebook/NAMAS#6]
I understand that you assume the use of [annotated gigaword](https://catalog.ldc.upenn.edu/LDC2012T21). but you also unparse the data in your preprocessing script. I wonder if I can use the [5th edition gigaword](https://catalog.ldc.upenn.edu/LDC2011T07) directly. Is there any gotcha's I need to watch for?

**Comment by supchop** [comment]
Since we do not actually use any annotations from the corpus, I don't anticipate any issue with using the 5th edition.

**Comment by falcondai** [comment]
thanks! i will come back with a link to my forked repo once I get that to work

**Comment by falcondai** [comment]
btw @supchop is the trained model posted anywhere? i am sure it will be useful for many people interested in this excellent work.

**Comment by falcondai** [comment]
For those interested in using the plain 5th edition gigaword dataset (https://catalog.ldc.upenn.edu/LDC2011T07). you can try my commit here: https://github.com/falcondai/NAMAS/commit/15427a48b414ca71b0b5fa3b45174d080c2556ef

The modification I made:
- I used NLTK `word_tokenize` to tokenize the text (which may result in different tokenization from the annotated gigaword) 
- I dropped article-title pairs that contains non-ASCII characters because it will cause errors in the tokenizer and it is known that gigaword contains some articles in non-English (Spanish). it would be better to remove these using the official list though.

After 20 epochs (default), I got similar validation perplexity (27.740008) as the number quoted in the paper, so i think these minor modifications do not affect the trained model significantly.

**Comment by supchop** [comment]
@falcondai Sorry for the late response. Unfortunately we are not able to post the trained model anywhere due to certain legal issues. Sorry. 

Thanks for creating a fork which tokenizes the 5th edition of the gigaword dataset.

**Comment by falcondai** [comment]
@supchop one followup to the legal issue posting trained models: can we, users of your repo, post our trained models (trained using some modified version of your code)? If that is okay, I am more than happy to post mine, especially after seeing some interest from other people here.

**Comment by supchop** [comment]
Yes. I believe you are free to post your trained model. There should not be
any problem with that. Thanks.

**Comment by falcondai** [comment]
here, posted: https://github.com/falcondai/trained-ABS-model
